
--============================================================
-------------------DATABASE EXPLORATION-----------------------
--============================================================

-- Explore All Objects in the Database
select * from INFORMATION_SCHEMA.TABLES


-- Explore All Columns in the Database

select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers'


--============================================================
-------------------DIMENSIONS EXPLORATION---------------------
--============================================================

--Explore ALL Countries our customers come from
SELECT DISTINCT country from gold.dim_customers

--Explore ALL Categories "The major Divisions"
SELECT DISTINCT category , subcategory , product_name FROM gold.dim_product
order by 1,2,3

--============================================================
-------------------DATE EXPLORATION---------------------
--============================================================

--Find the date of the first and last order
select 
min(order_date) first_order_date ,
max(order_date) last_order_date
from gold.fact_sales

--How many years of sales are available
select 
datediff(YEAR, min(order_date), max(order_date) )
from gold.fact_sales

--Find the youngest and oldest customer
select 
MIN(birthdate) oldest_customer,
MAX(birthdate) youngest_birthdate
from gold.dim_customers

--Ages of youngest and oldest Customers
select 
DATEDIFF(YEAR , MIN(birthdate) , GETDATE()) ,
DATEDIFF(YEAR , MAX(birthdate) , GETDATE())
from gold.dim_customers


--============================================================
-------------------Measures Explorations---------------------
--============================================================

--Find the Total Sales
select sum(sales_amount) As total_sales
from gold.fact_sales

--Find how many items are sold
select SUM(quantity) As items_sold from gold.fact_sales

--Find the average selling price
select avg(price) As average_selling_price from gold.fact_sales

--Find the Total number of Orders
select count(order_number) As total_orders from gold.fact_sales
select count(DISTINCT order_number) As total_orders from gold.fact_sales

--Find the Total number of products
select count(DISTINCT product_id) As total_products from gold.dim_product

--Find the Total number of customers
select count(Distinct customer_id) As total_customer from gold.dim_customers

--Find the total number of customers that has places an order
select count(DISTINCT customer_key) As total_customer_placed from gold.fact_sales


-- Generate a Report that shows all key metrics of the business
select 'Total Sales' As measure_name ,sum(sales_amount) As measure_value from gold.fact_sales
Union All
select 'Total Quantity' As measure_name ,sum(quantity) As measure_value from gold.fact_sales
Union All
select 'Avg Price' as measure_name , avg(price) As measure_value from gold.fact_sales
Union All
select 'Total Nr. Orders' as measure_name , count(DISTINCT order_number) As measure_value from gold.fact_sales
Union ALL
select 'Total Nr. Products' as measure_name , count(product_name) As measure_value from gold.dim_product
Union ALL
select 'Total Nr. Customers' as measure_name , count(customer_key) As measure_value from gold.dim_customers



--============================================================
-------------------------Magnitude----------------------------
--============================================================

--Find total customers by countries
select
cu.country,
count(cu.customer_key) As total_customers
from gold.dim_customers as cu
group by cu.country
ORDER BY total_customers DESC


--Find total customers by gender
select
cu.gender,
count(cu.customer_key) As total_customers
from gold.dim_customers as cu
group by cu.gender
ORDER BY total_customers DESC


--Find total products by category
select
category,
count(product_key) As total_products
from gold.dim_product
group by category
order by total_products DESC


--What is the averaage costs in each category?
select
category,
AVG(cost) As avg_costs
from gold.dim_product
group by category
order by avg_costs DESC


--What is the total revenue generated for each category?
SELECT
p.category,
sum(f.sales_amount) AS total_revenue
From gold.fact_sales f
LEFT JOIN gold.dim_product p
on p.product_key = f.product_key
GROUP BY p.category 
ORDER BY total_revenue DESC


--Find total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) As total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

--what is the distribution of sold items across countries?
select c.country,
SUM(f.quantity) AS total_revenue
from gold.fact_sales as f
LEFT JOIN gold.dim_customers as c
on c.customer_key = f.customer_key
group by c.country
order by total_revenue DESC


--============================================================
---------------------------Ranking----------------------------
--============================================================

--Which 5 products generate the highest revenue?
select TOP 5 
p.product_name,
sum(s.sales_amount) as total_sales
from gold.fact_sales s
LEFT JOIN gold.dim_product p
on p.product_key = s.product_key
GROUP BY p.product_name
order by total_sales DESC


--What are the 5 worst-performing products in terms of sales?
select TOP 5 
p.product_name,
sum(s.sales_amount) as total_sales
from gold.fact_sales s
LEFT JOIN gold.dim_product p
on p.product_key = s.product_key
GROUP BY p.product_name
order by total_sales Asc

--Find the Top-10 customers who have generated the highest revenue
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key = f.customer_key
GROUP BY c.customer_key,c.first_name , c.last_name
ORDER BY total_revenue DESC

--The 3 customer with the fewest orders placed
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_order
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key = f.customer_key
GROUP BY c.customer_key,c.first_name , c.last_name
ORDER BY total_order ASC



